<b>Q1)<b/> Write a code to perform Gauss elimination with and without pivoting for a 2 x 2 system, taking the number of significant digits (d) to be considered
as user input. Using the code, solve the 2 x 2 system with random coefficients for d = 3, 4, 5 and 6. Display the results in a tabular form.

In [102]:
import numpy as np

def elimination(matrix, row):
#   get no of rows
    n = matrix.shape[0]
    for i in range(row + 1, n):
        if (matrix[row][row] != 0):
            fact = matrix[i][row] / matrix[row][row]
            for j in range(i):
                matrix[i][j] = 0
            for j in range(i, n + 1):
                matrix[i][j] = matrix[i][j] - fact * matrix[row][j]
        
def pivot(matrix, col):
#   get no of rows
    n = matrix.shape[0]
    m = col
    for i in range(col + 1, n):
        if (abs(matrix[i][col]) > abs(matrix[m][col])):
            m = i
    if (col != m):
        matrix[[col,m]] = matrix[[m,col]]
        
def back_substitution(matrix):
#   get no of rows
    n = matrix.shape[0]
    res = np.zeros(n)
    for i in range(n - 1, -1, -1):
        total = 0.0
        for j in range(n - 1, i, -1):
            total += res[j] * matrix[i][j]
        res[i] = (matrix[i][n] - total) / matrix[i][i]
    return res

n = 2 # int(input("Enter the size of matrix\n"))
# for augmented matrix adding 1 extra column
# setting random values
m = np.random.rand(n, n + 1)
# Running for significant digits 3, 4, 5, 6
for s_d in range(3, 7):
    print("Significant digits ", s_d)
    matrix = np.zeros((n, n + 1))
    for i in range(n):
        for j in range(n + 1):
#           rounding off to significant digits and assigning to matrix
            matrix[i][j] = round(m[i][j], s_d)
#   copying the matrix to perform pivot
#   pivoting donde for matrix_cp and no pivoting for matrix
    matrix_cp = matrix.copy()
    print (matrix)

    for i in range(n - 1):
        elimination(matrix, i)
        pivot(matrix_cp, i)
        elimination(matrix_cp, i)

    result_without_pivot = back_substitution(matrix)
    result_with_pivot = back_substitution(matrix_cp)

    print ("Result with pivot", result_with_pivot)
    print ("Result without pivot", result_without_pivot)

Significant digits  3
[[0.393 0.428 0.501]
 [0.159 0.747 0.649]]
Result with pivot [0.42779101 0.77775265]
Result without pivot [0.42779101 0.77775265]
Significant digits  4
[[0.3933 0.428  0.5014]
 [0.1589 0.747  0.6492]]
Result with pivot [0.42822958 0.77798436]
Result without pivot [0.42822958 0.77798436]
Significant digits  5
[[0.39327 0.42803 0.50144]
 [0.15893 0.74697 0.64917]]
Result with pivot [0.42836421 0.7779296 ]
Result without pivot [0.42836421 0.7779296 ]
Significant digits  6
[[0.393272 0.428033 0.501442]
 [0.158934 0.746971 0.649167]]
Result with pivot [0.42837068 0.77792088]
Result without pivot [0.42837068 0.77792088]
